namespace Pixata.Blazor.Sample.Shared {
  public class IconsHelper {
    public static string Address = "fa fa-address-card";
    public static string Agents = "fas fa-fw fa-user-tag";
    public static string Alignment = "fad fa-align-right";
    public static string AngleRight = "fas fa-angle-right";
    public static string Attachment = "fa fa-paperclip";
    public static string Bank = "far fa-money-check-edit";
    public static string Bin = "k-icon k-i-trash";
    public static string Birthday = "fa fa-birthday-cake"; // Use for date of birth
    public static string Bookmark = "fa fa-bookmark";
    public static string Building = "fa fa-building"; // Use for company name
    public static string Briefcase = "oi oi-briefcase";
    public static string Calender = "fas fa-calendar-alt";
    public static string CalenderPencil = "fal fa-calendar-edit";
    public static string Cancel = "fa fa-undo-alt";
    public static string Cash = "fas fa-cash-register";
    public static string Chat = "oi oi-chat";
    public static string Child = "far fa-child";
    public static string Clock = "oi oi-clock";
    public static string Cog = "oi oi-cog";
    public static string Coins = "fas fa-fw fa-coins";
    public static string Companies = "fas fa-fw fa-building";
    public static string Contractors = "fas fa-fw fa-hard-hat";
    public static string Dashboard = "far fa-tachometer-alt-fast";
    public static string DocumentChart = "far fa-file-medical-alt";
    public static string DocumentUser = "far fa-file-user";
    public static string DataTransferDownload = "oi oi-data-transfer-download";
    public static string Edit = "k-icon k-i-edit";
    public static string Email = "fa fa-at";
    public static string Envelope = "fa fa-envelope";
    public static string ExternalLink = "oi oi-external-link";
    public static string Fee = "fal fa-money-check-edit";
    public static string House = "fa fa-home";
    public static string IdCard = "fa fa-id-card";
    public static string Info = "oi oi-info";
    public static string Initial = "fab fa-autoprefixer";
    public static string Investors = "fas fa-fw fa-hand-holding-usd";
    public static string Key = "fad fa-key";
    public static string LinkBroken = "oi oi-link-broken";
    public static string LogIn = "oi oi-account-login";
    public static string LogOut = "fa fa-sign-out-alt";
    public static string Mobile = "fa fa-mobile-alt";
    public static string Network = "far fa-chart-network";
    public static string Party = "fas fa-birthday-cake"; // Use for parties (as in secondary, but I couldn't find a suitable icon so did a play on words)
    public static string Plus = "k-icon k-i-plus";
    public static string Percent = "fas fa-percent";
    public static string Person = "oi oi-person";
    public static string Phone = "fa fa-phone";
    public static string Postcode = "fa fa-road";
    public static string Property = "fas fa-house";
    public static string Properties = "fas fa-fw fa-home";
    public static string Redo = "fa fa-redo";
    public static string Register = "fad fa-align-left";
    public static string Reports = "fas fa-fw fa-flag";
    public static string Role = "fad fa-user-tag";
    public static string Save = "fa fa-sign-in-alt";
    public static string Salutation = "fad fa-handshake-alt";
    public static string Search = "fas fa-search";
    public static string Send = "fa fa-paper-plane";
    public static string Signature = "fa fa-signature";
    public static string Spinner = "spinner-border spinner-border-sm";
    public static string Subject = "fa fa-envelope-open";
    public static string Tag = "fa fa-tag";
    public static string Task = "oi oi-task";
    public static string TelephoneModern = "fa fa-phone-office";
    public static string TelephoneOld = "fa fa-phone-rotary"; // Use this first, and only use TelephoneModern if you need a second icon
    public static string Title = "fad fa-helmet-battle";
    public static string User = "fa fa-user"; // Main one to use for a user
    public static string UserCog = "fa fa-user-cog";
    public static string UserAlt = "fas fa-user-astronaut";
    public static string UserFas = "fas fa-user";
    public static string Users = "fad fa-users-class";
  }
}