<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Version>2.16.0</Version>
    <AssemblyVersion>2.16.0</AssemblyVersion>
    <FileVersion>2.16.0</FileVersion>
    <Company>Pixata Ltd</Company>
    <Authors>Avrohom Yisroel Silver</Authors>
    <Product>Pixata.Extensions</Product>
    <Description>A set of C# extension methods that I found useful. See the GitHub page for more information</Description>
    <ProjectUrl>https://github.com/MrYossu/Pixata.Utilities/tree/master/Pixata.Extensions</ProjectUrl>
    <PackageProjectUrl>https://github.com/MrYossu/Pixata.Utilities/tree/master/Pixata.Extensions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MrYossu/Pixata.Utilities/tree/master/Pixata.Extensions</RepositoryUrl>
    <Copyright>Copyright 2026 Pixata Ltd</Copyright>
    <PackageTags>C# extension-methods</PackageTags>
    <PackageIcon>VroumVroum.png</PackageIcon>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="VroumVroum.png" Pack="true" PackagePath="\" />
    <None Include="Readme.md" Pack="True" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
  </ItemGroup>

</Project>