namespace Pixata.AspNetCore.Pdf;

public enum PdfOrientation {
  Portrait,
  Landscape
}

public enum PdfPaperSize {
  A3,
  A4,
  A4Plus,
  A5,
  Letter,
  Legal
}

/// <summary>
/// Page settings for a PDF generated by a <see cref="PdfConverterInterface"/>
/// </summary>
public class PdfOptions {
  public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;
  public PdfPaperSize PaperSize { get; set; } = PdfPaperSize.A4;

  /// <summary>
  /// The page margins, in millimetres
  /// </summary>
  public double MarginMm { get; set; } = 10;

  /// <summary>
  /// The base URL the HTML was rendered with. Converters use this to resolve relative URLs, and only load images from this site (or from
  /// <c>data:</c> URIs), so that user-supplied content in the HTML can't make the server fetch arbitrary URLs. <see cref="Helpers.DocumentTemplateHelper"/>
  /// sets this for you
  /// </summary>
  public string BaseUrl { get; set; } = "";

  /// <summary>
  /// The paper size in millimetres (width, height) in portrait orientation
  /// </summary>
  public (double Width, double Height) PaperSizeMm() =>
    PaperSize switch {
      PdfPaperSize.A3 => (297, 420),
      PdfPaperSize.A4 => (210, 297),
      PdfPaperSize.A4Plus => (225, 320),
      PdfPaperSize.A5 => (148, 210),
      PdfPaperSize.Letter => (215.9, 279.4),
      PdfPaperSize.Legal => (215.9, 355.6),
      _ => throw new ArgumentOutOfRangeException(nameof(PaperSize))
    };
}
