name: .NET Core  
  
on:  
  push:  
    branches: [ master ]  
  pull_request:  
    branches: [ master ]  
  
jobs:  
  build:  
  
    runs-on: windows-latest  
  
    env:
      TELERIK_USERNAME: ${{secrets.TELERIK_USERNAME}}
      TELERIK_PASSWORD: ${{secrets.TELERIK_PASSWORD}}
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v1.7.2  
      with:  
        dotnet-version: '5.0'
    - name: Install dependencies  
      run: dotnet restore  
    - name: Build  
      run: dotnet build --configuration Release --no-restore  
    - name: Test  
      run: dotnet test --no-restore --verbosity normal 
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
       PROJECT_FILE_PATH: Pixata.Blazor/Pixata.Blazor.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
