name: Pixata.Blazor
  
on:  
  push:  
    branches: [ master ]  
  pull_request:  
    branches: [ master ]  
  
  workflow_dispatch:

jobs:  
  build:  
  
    runs-on: windows-latest  
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v1.7.2  
      with:  
        dotnet-version: '5.0'
    - name: Install dependencies  
      run: dotnet restore --configfile Nuget.config
      env:
        Actions_Allow_Unsecure_Commands: true
        TELERIK_USERNAME: ${{secrets.MyTelerikAccountUsername}}
        TELERIK_PASSWORD: ${{secrets.MyTelerikAccountPassword}}
    - name: Build  
      run: dotnet build --configuration Release --configfile Nuget.config
      env:
        Actions_Allow_Unsecure_Commands: true
        TELERIK_USERNAME: ${{secrets.MyTelerikAccountUsername}}
        TELERIK_PASSWORD: ${{secrets.MyTelerikAccountPassword}}
    - name: Test  
      run: dotnet test --verbosity normal 
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
       PROJECT_FILE_PATH: Pixata.Blazor/Pixata.Blazor.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
